### ISSUE TITLE
Error: The YouTube API key you provided was not a string.

### ISSUE THREAD

**Issue by SpinneySpinster** [zyrouge/eris-music-bot#3]
I keep getting this error:

![Screen Shot 2020-06-23 at 10 23 53 PM](https://user-images.githubusercontent.com/67039094/85500191-48dc1880-b5a0-11ea-8891-b1fa0399aeee.png)

 and I'm not finding anything helpful on how to fix it. Can anyone help?

**Comment by zyrouge** [comment]
Adding `YTTOKEN` in `.env` should fix it
